---
- name: "Preflight - Fail if target host is not stable for this Role."
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in supervisor_stable_os)

- name: "Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Ensure Supervisor is installed."
  package:
    name: supervisor
    state: present

- name: "Ensure Supervisor log dir exists."
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- name: "Ensure Supervisor config paths are present."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ supervisor_config_path }}"
    - "{{ supervisor_config_path }}/conf.d"

- name: "Ensure Supervisor configuration is present."
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_config_path }}/supervisord.conf"
    mode: 0644
  notify: restart supervisor

- name: "Ensure Supervisor program configs are present."
  template:
    src: program.conf.j2
    dest: "{{ supervisor_config_path }}/conf.d/{{ item.name }}.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ supervisor_programs }}"
  notify: restart supervisor

- name: "Ensure Supervisor is started (if configured)."
  service:
    name: "{{ supervisor_name }}"
    state: started
  when: supervisor_started

- name: "Ensure Supervisor is enabled at boot (if configured)."
  service:
    name: "{{ supervisor_name }}"
    enabled: true
  when: supervisor_enabled
