---
- name: Preflight - Fail if target host is not stable for this Role.
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in supervisor_stable_os)

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Supervisor is installed (specific version).
  package:
    name: supervisor
    state: present
    version: "{{ supervisor_version }}"
  when: supervisor_version != 'latest'

- name: Ensure Supervisor is installed (latest version).
  package:
    name: supervisor
    state: present
  when: supervisor_version == 'latest'

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755

- include: config.yml

# Currently commented out, as we want to use the configuration delivered by the package manager
#- include: init-setup.yml
#  when: supervisor_started or supervisor_enabled

- name: Ensure Supervisor is started (if configured).
  service:
    name: "{{ supervisor_name }}"
    state: started
  when: supervisor_started

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: "{{ supervisor_name }}"
    enabled: true
  when: supervisor_enabled
